---
- name: Add repository
  include_role:
    name: packagecloud
  vars:
      repository: scalr/scalr-server-ee
      os: "{{ ansible_distribution }}"
      version: "{{ ansible_distribution_major_version }}"
      master_token: "{{ repokey }}"

- name: update cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: create scalr directory
  file:
    path: /etc/scalr-server
    state: directory

- name: install scalr
  package:
    name: scalr-server

# - name: copy license file in
#   copy:
#     src: "{{ path_to_license }}"
#     dest: /etc/scalr-server/license.json

- name: secrets file
  command: /usr/bin/scalr-server-wizard

- name: all in one template in config
  template:
    src: "{{ role_path }}/templates/scalr-server.rb.tmp"
    dest: /etc/scalr-server/scalr-server.rb
  notify: reconfigure scalr
